Add optional param for AWS IAM role assumption
meltwater/drone-cache pull request #143
Opened 2020-11-05 18:39 UTC by hhamalai

Fixes #142

## Proposed Changes
- add flag to specify role arn
- if role arn is specified, use access keys to assume the role with arn provided

### Description
Allows specifying role ARN which, if specified, is assumed with STS. All S3 operations are executed with this role.

### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [ ] Add tests to cover changes.
- [x] Ensure your code follows the code style of this project.
- [ ] Ensure CI and all other PR checks are green OR
    - [ ] Code compiles correctly.
    - [ ] Created tests which fail without the change (if possible).
    - [ ] All new and existing tests passed.
- [ ] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).
- [ ] Improve and update the [README](README.md) (if necessary).
- [ ] Ensure [documentation](./DOCS.md) is up-to-date. The same file will be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) when your PR is accepted, so it will be available for end-users at http://plugins.drone.io.

2020-11-06 08:27 UTC, kakkoyun requested changes
Looking good. Thanks a lot for the contribution. 

Is there way to test thing with our setup? We have minio, it'd be good to have tests.

2020-11-06 08:27 UTC, kakkoyun commented on storage/backend/s3/config.go
> +	RoleArn    string // if "", do not assume IAM role i.e. use the IAM user
nit
```suggestion
	RoleArn    string // if "", do not assume IAM role i.e. use the IAM user.
```

2020-11-06 08:41 UTC, hhamalai commented
> Is there way to test thing with our setup? We have minio, it'd be good to have tests.

I didn't see any authentication related tests in the code, at least for AWS. What's your take on mocked unit tests, that would be plausible, but I can also check the minio support for role assumption as documented here  https://github.com/minio/minio/blob/master/docs/sts/assume-role.md

2020-11-06 09:33 UTC, kakkoyun commented
@hhamalai 
We have rudimentary happy path tests in the form of high-level e2e tests in here https://github.com/meltwater/drone-cache/blob/c6fa14678b59d689c99f28655880031a80911be7/internal/plugin/plugin_test.go#L386

What we can either extend those or even better add a specific case in here https://github.com/meltwater/drone-cache/blob/master/storage/backend/s3/s3_test.go

Even a simple one to prevent regressions would suffice.

2020-11-09 16:11 UTC, hhamalai commented on storage/backend/s3/config.go
> +	RoleArn    string // if "", do not assume IAM role i.e. use the IAM user
fixed

2020-11-09 16:50 UTC, hhamalai commented
Hi, I added the test case, unfortunately it required quite a bit of too many changes. I am still not too familiar with minio, so take the following findings with a grain of salt:

1. need newer version minio in order to support STS operations
2. need a creation of users an policies on minio as the admin user cannot use STS (in docker-compose & drone yaml)

2020-11-10 09:01 UTC, kakkoyun approved these changes
Wow, what a great PR! Thank you very much for this contribution and level of code quality.

It looks good to me. I have only requested a single change concerning package imports. If you can fix it I'll merge this immediately.

2020-11-10 09:41 UTC, kakkoyun approved these changes

2020-11-10 09:42 UTC, merged